services:
  # 1. Backend REST API Service
  - type: web
    name: spendwise-backend-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://khanovez257_db_user:CPVPPrzBRdLO9GUr@cluster0.qbsrsm9.mongodb.net/expense_tracker?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 5000

  # 2. Frontend React SPA Static Site
  - type: web
    name: spendwise-frontend-app
    env: static
    rootDir: client
    buildCommand: npm run build
    staticPublishPath: dist
